name: Auto Bump Casks

on:
  schedule:
    # Every 5 days at China time 00:00 (UTC 16:00 previous day)
    - cron: '0 16 1,6,11,16,21,26,31 * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Auto-bump casks
        uses: Homebrew/actions/bump-formulae@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tap: lz-lunzi/homebrew-buket
          formulae-dir: Casks
